on:
  pull_request:
    branches:
      - main

jobs:
  sticky_comment_test_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Write down sticky comment
        id: sticky-step
        uses: nalch/sticky-comment@v4
        with:
          id: what
          content: 'Yeehaw'

